import { AuthProvider, LayoutProvider, LoadingProvider } from "../providers";
import "../globals.css";
import localFont from "next/font/local";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className={"auth-layout-body"} suppressHydrationWarning>
        <AuthProvider>
          <LayoutProvider>
            <LoadingProvider>{children}</LoadingProvider>
          </LayoutProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
